// AUTO-GENERATED from the client's real list: "standard list 2026 (Autosaved).xlsx".
// Real category + product names + box content (QTY). Prices NOT in the client sheet →
// mrp/price = 0 (shown as "—"); the owner fills prices in /admin/products.

export type SeedCategory = { id: string; line: "standard" | "elite"; name: string };
export type SeedProduct = {
  id: string; categoryId: string; name: string; content: string; mrp: number; price: number;
};

export const SEED_CATEGORIES: SeedCategory[] = [
  { id: "standard-sparklers", line: "standard", name: "Sparklers" },
  { id: "standard-chakkars", line: "standard", name: "Chakkars" },
  { id: "standard-flower-pots", line: "standard", name: "Flower Pots" },
  { id: "standard-fancy-fountains-5-piece", line: "standard", name: "Fancy Fountains 5 Piece" },
  { id: "standard-novel-fireworks-20-piece", line: "standard", name: "Novel Fireworks 20 Piece" },
  { id: "standard-one-sound-crackers", line: "standard", name: "One Sound Crackers" },
  { id: "standard-premium-fancy-fireworks", line: "standard", name: "Premium Fancy Fireworks" },
  { id: "standard-attom-bomb", line: "standard", name: "Attom Bomb" },
  { id: "standard-rockets", line: "standard", name: "Rockets" },
  { id: "standard-fancy-fireworks", line: "standard", name: "Fancy Fireworks" },
  { id: "standard-multishots", line: "standard", name: "Multishots" },
  { id: "standard-comets", line: "standard", name: "Comets" },
  { id: "standard-confetti-colour-smoke", line: "standard", name: "Confetti & Colour Smoke" },
  { id: "standard-gift-box", line: "standard", name: "Gift Box" },
  { id: "standard-0-75-cakes", line: "standard", name: "0.75 Cakes" },
  { id: "elite-sparklers", line: "elite", name: "Sparklers" },
  { id: "elite-flower-pot", line: "elite", name: "Flower Pot" },
  { id: "elite-ground-chakkar", line: "elite", name: "Ground Chakkar" },
  { id: "elite-twinking-star", line: "elite", name: "Twinking Star" },
  { id: "elite-one-sound-crackers", line: "elite", name: "One Sound Crackers" },
  { id: "elite-bomb", line: "elite", name: "Bomb" },
  { id: "elite-paper-bomb", line: "elite", name: "Paper Bomb" },
  { id: "elite-rocket", line: "elite", name: "Rocket" },
  { id: "elite-night-fancy", line: "elite", name: "Night Fancy" },
  { id: "elite-peacock", line: "elite", name: "Peacock" },
  { id: "elite-comets", line: "elite", name: "Comets" },
  { id: "elite-multi-shots", line: "elite", name: "Multi Shots" },
  { id: "elite-matches", line: "elite", name: "Matches" },
  { id: "elite-gift-box", line: "elite", name: "Gift Box" },
];

export const SEED_PRODUCTS: SeedProduct[] = [
  { id: "standard-sparklers-1", categoryId: "standard-sparklers", name: "Jimmy Gold 12cm", content: "10 Pcs", mrp: 0, price: 0 },
  { id: "standard-sparklers-2", categoryId: "standard-sparklers", name: "Jimmy Clarckling 12cm", content: "10 Pcs", mrp: 0, price: 0 },
  { id: "standard-sparklers-3", categoryId: "standard-sparklers", name: "Gold 15cm", content: "10 Pcs", mrp: 0, price: 0 },
  { id: "standard-sparklers-4", categoryId: "standard-sparklers", name: "Crackiling 15cm", content: "10 Pcs", mrp: 0, price: 0 },
  { id: "standard-sparklers-5", categoryId: "standard-sparklers", name: "Gold 30cm", content: "5 Pcs", mrp: 0, price: 0 },
  { id: "standard-sparklers-6", categoryId: "standard-sparklers", name: "Crackling 30cm", content: "5 Pcs", mrp: 0, price: 0 },
  { id: "standard-sparklers-7", categoryId: "standard-sparklers", name: "Lemon Tree Sparklers 15cm", content: "10 Pcs", mrp: 0, price: 0 },
  { id: "standard-sparklers-8", categoryId: "standard-sparklers", name: "Lavender 15cm", content: "10 Pcs", mrp: 0, price: 0 },
  { id: "standard-chakkars-1", categoryId: "standard-chakkars", name: "Zamin Chakkars Big", content: "25 Pcs", mrp: 0, price: 0 },
  { id: "standard-chakkars-2", categoryId: "standard-chakkars", name: "Zamin Chakkars Special", content: "10 Pcs", mrp: 0, price: 0 },
  { id: "standard-chakkars-3", categoryId: "standard-chakkars", name: "Zamin Chakkars Deluxe", content: "10 Pcs", mrp: 0, price: 0 },
  { id: "standard-chakkars-4", categoryId: "standard-chakkars", name: "Whizzwheel", content: "5 Pcs", mrp: 0, price: 0 },
  { id: "standard-chakkars-5", categoryId: "standard-chakkars", name: "Red &white Chakkars", content: "5 Pcs", mrp: 0, price: 0 },
  { id: "standard-flower-pots-1", categoryId: "standard-flower-pots", name: "Big", content: "10 Pcs", mrp: 0, price: 0 },
  { id: "standard-flower-pots-2", categoryId: "standard-flower-pots", name: "Special", content: "10 Pcs", mrp: 0, price: 0 },
  { id: "standard-flower-pots-3", categoryId: "standard-flower-pots", name: "Gaints", content: "10 Pcs", mrp: 0, price: 0 },
  { id: "standard-flower-pots-4", categoryId: "standard-flower-pots", name: "Deluxe", content: "5 Pcs", mrp: 0, price: 0 },
  { id: "standard-flower-pots-5", categoryId: "standard-flower-pots", name: "Tri Color Fountains", content: "5 Pcs", mrp: 0, price: 0 },
  { id: "standard-fancy-fountains-5-piece-1", categoryId: "standard-fancy-fountains-5-piece", name: "Mini Fountain Red", content: "5 Pcs", mrp: 0, price: 0 },
  { id: "standard-fancy-fountains-5-piece-2", categoryId: "standard-fancy-fountains-5-piece", name: "Jet Foutain", content: "5 Pcs", mrp: 0, price: 0 },
  { id: "standard-fancy-fountains-5-piece-3", categoryId: "standard-fancy-fountains-5-piece", name: "Crackling King", content: "5 Pcs", mrp: 0, price: 0 },
  { id: "standard-fancy-fountains-5-piece-4", categoryId: "standard-fancy-fountains-5-piece", name: "Lavender Fountain", content: "5 Pcs", mrp: 0, price: 0 },
  { id: "standard-fancy-fountains-5-piece-5", categoryId: "standard-fancy-fountains-5-piece", name: "Cheers", content: "3 Pcs", mrp: 0, price: 0 },
  { id: "standard-fancy-fountains-5-piece-6", categoryId: "standard-fancy-fountains-5-piece", name: "Colour Fountain", content: "4 Pcs", mrp: 0, price: 0 },
  { id: "standard-novel-fireworks-20-piece-1", categoryId: "standard-novel-fireworks-20-piece", name: "45cm Twliking Star", content: "10 Pcs", mrp: 0, price: 0 },
  { id: "standard-novel-fireworks-20-piece-2", categoryId: "standard-novel-fireworks-20-piece", name: "60cm", content: "10 Pcs", mrp: 0, price: 0 },
  { id: "standard-novel-fireworks-20-piece-3", categoryId: "standard-novel-fireworks-20-piece", name: "Multicolour Candel", content: "10 Pcs", mrp: 0, price: 0 },
  { id: "standard-one-sound-crackers-1", categoryId: "standard-one-sound-crackers", name: "Red Bigili 100 Piece", content: "1 Bag", mrp: 0, price: 0 },
  { id: "standard-one-sound-crackers-2", categoryId: "standard-one-sound-crackers", name: "Striped Bigili 100 Piece", content: "1 Bag", mrp: 0, price: 0 },
  { id: "standard-one-sound-crackers-3", categoryId: "standard-one-sound-crackers", name: "6.5cm Sparrow", content: "5 Pcs", mrp: 0, price: 0 },
  { id: "standard-one-sound-crackers-4", categoryId: "standard-one-sound-crackers", name: "9cm Lakashmi", content: "5 Pcs", mrp: 0, price: 0 },
  { id: "standard-one-sound-crackers-5", categoryId: "standard-one-sound-crackers", name: "10cm Krishna", content: "5 Pcs", mrp: 0, price: 0 },
  { id: "standard-one-sound-crackers-6", categoryId: "standard-one-sound-crackers", name: "9cm Two Sound", content: "5 Pcs", mrp: 0, price: 0 },
  { id: "standard-premium-fancy-fireworks-1", categoryId: "standard-premium-fancy-fireworks", name: "Magic Crackers -28", content: "1 Pcs", mrp: 0, price: 0 },
  { id: "standard-premium-fancy-fireworks-2", categoryId: "standard-premium-fancy-fireworks", name: "Magic Crackers -56", content: "1 Pcs", mrp: 0, price: 0 },
  { id: "standard-premium-fancy-fireworks-3", categoryId: "standard-premium-fancy-fireworks", name: "Magic Crackers -100", content: "1 Pcs", mrp: 0, price: 0 },
  { id: "standard-premium-fancy-fireworks-4", categoryId: "standard-premium-fancy-fireworks", name: "Magic Crackers -1000", content: "1 Pcs", mrp: 0, price: 0 },
  { id: "standard-premium-fancy-fireworks-5", categoryId: "standard-premium-fancy-fireworks", name: "Magic Crackers -2000", content: "1 Pcs", mrp: 0, price: 0 },
  { id: "standard-premium-fancy-fireworks-6", categoryId: "standard-premium-fancy-fireworks", name: "Magic Crackers -5000", content: "1 Pcs", mrp: 0, price: 0 },
  { id: "standard-premium-fancy-fireworks-7", categoryId: "standard-premium-fancy-fireworks", name: "Magic Crackers -10000", content: "1 Pcs", mrp: 0, price: 0 },
  { id: "standard-attom-bomb-1", categoryId: "standard-attom-bomb", name: "Std Hydrogen Green", content: "10 Pcs", mrp: 0, price: 0 },
  { id: "standard-attom-bomb-2", categoryId: "standard-attom-bomb", name: "Hydrogen Bomb", content: "10 Pcs", mrp: 0, price: 0 },
  { id: "standard-attom-bomb-3", categoryId: "standard-attom-bomb", name: "Thunder Bomb", content: "10 Pcs", mrp: 0, price: 0 },
  { id: "standard-rockets-1", categoryId: "standard-rockets", name: "Rainbow", content: "10 Pcs", mrp: 0, price: 0 },
  { id: "standard-rockets-2", categoryId: "standard-rockets", name: "Rohini", content: "10 Pcs", mrp: 0, price: 0 },
  { id: "standard-rockets-3", categoryId: "standard-rockets", name: "Bomb Rocket", content: "10 Pcs", mrp: 0, price: 0 },
  { id: "standard-fancy-fireworks-1", categoryId: "standard-fancy-fireworks", name: "Cluster Blaster", content: "1 Pcs", mrp: 0, price: 0 },
  { id: "standard-fancy-fireworks-2", categoryId: "standard-fancy-fireworks", name: "Happy Dreams", content: "1 Pcs", mrp: 0, price: 0 },
  { id: "standard-fancy-fireworks-3", categoryId: "standard-fancy-fireworks", name: "Snow Walley", content: "1 Pcs", mrp: 0, price: 0 },
  { id: "standard-fancy-fireworks-4", categoryId: "standard-fancy-fireworks", name: "Chat Chat", content: "10 Pcs", mrp: 0, price: 0 },
  { id: "standard-fancy-fireworks-5", categoryId: "standard-fancy-fireworks", name: "Signal Light", content: "10 Pcs", mrp: 0, price: 0 },
  { id: "standard-fancy-fireworks-6", categoryId: "standard-fancy-fireworks", name: "Colour Changing Butterfly", content: "5 Pcs", mrp: 0, price: 0 },
  { id: "standard-fancy-fireworks-7", categoryId: "standard-fancy-fireworks", name: "Golden Whistle Small", content: "5 Pcs", mrp: 0, price: 0 },
  { id: "standard-fancy-fireworks-8", categoryId: "standard-fancy-fireworks", name: "Gold Rush", content: "5 Pcs", mrp: 0, price: 0 },
  { id: "standard-fancy-fireworks-9", categoryId: "standard-fancy-fireworks", name: "Aerial Out", content: "5 Pcs", mrp: 0, price: 0 },
  { id: "standard-fancy-fireworks-10", categoryId: "standard-fancy-fireworks", name: "Seven Shots", content: "5 Pcs", mrp: 0, price: 0 },
  { id: "standard-fancy-fireworks-11", categoryId: "standard-fancy-fireworks", name: "Disco Flash", content: "6 Pcs", mrp: 0, price: 0 },
  { id: "standard-fancy-fireworks-12", categoryId: "standard-fancy-fireworks", name: "Krack Jak", content: "3 Pcs", mrp: 0, price: 0 },
  { id: "standard-fancy-fireworks-13", categoryId: "standard-fancy-fireworks", name: "Dollor Wheel", content: "5 Pcs", mrp: 0, price: 0 },
  { id: "standard-fancy-fireworks-14", categoryId: "standard-fancy-fireworks", name: "Poker Wheel", content: "5 Pcs", mrp: 0, price: 0 },
  { id: "standard-fancy-fireworks-15", categoryId: "standard-fancy-fireworks", name: "Couckoo", content: "5 Pcs", mrp: 0, price: 0 },
  { id: "standard-fancy-fireworks-16", categoryId: "standard-fancy-fireworks", name: "Lazer Show", content: "3 Pcs", mrp: 0, price: 0 },
  { id: "standard-fancy-fireworks-17", categoryId: "standard-fancy-fireworks", name: "Jil Junk Juk", content: "3 Pcs", mrp: 0, price: 0 },
  { id: "standard-fancy-fireworks-18", categoryId: "standard-fancy-fireworks", name: "Sun Drops", content: "5 Pcs", mrp: 0, price: 0 },
  { id: "standard-multishots-1", categoryId: "standard-multishots", name: "12 Shot (8 Variants)", content: "1 Pcs", mrp: 0, price: 0 },
  { id: "standard-multishots-2", categoryId: "standard-multishots", name: "20 Shots 8v", content: "1 Pcs", mrp: 0, price: 0 },
  { id: "standard-multishots-3", categoryId: "standard-multishots", name: "25 Shots 3v", content: "1 Pcs", mrp: 0, price: 0 },
  { id: "standard-multishots-4", categoryId: "standard-multishots", name: "30 Shots 3v", content: "1 Pcs", mrp: 0, price: 0 },
  { id: "standard-multishots-5", categoryId: "standard-multishots", name: "40 Shots 10v", content: "1 Pcs", mrp: 0, price: 0 },
  { id: "standard-multishots-6", categoryId: "standard-multishots", name: "60 Shots4v", content: "1 Pcs", mrp: 0, price: 0 },
  { id: "standard-multishots-7", categoryId: "standard-multishots", name: "100 Shots 4v", content: "1 Pcs", mrp: 0, price: 0 },
  { id: "standard-multishots-8", categoryId: "standard-multishots", name: "120 Shots 4v", content: "1 Pcs", mrp: 0, price: 0 },
  { id: "standard-multishots-9", categoryId: "standard-multishots", name: "240 Shots", content: "1 Pcs", mrp: 0, price: 0 },
  { id: "standard-comets-1", categoryId: "standard-comets", name: "1 Super Star 10v", content: "1 Pcs", mrp: 0, price: 0 },
  { id: "standard-comets-2", categoryId: "standard-comets", name: "1 1/4 Comets Star Fire 6v", content: "1 Pcs", mrp: 0, price: 0 },
  { id: "standard-comets-3", categoryId: "standard-comets", name: "1.25 Comets Avengers Special", content: "1 Pcs", mrp: 0, price: 0 },
  { id: "standard-comets-4", categoryId: "standard-comets", name: "1 3/4 Comets 3v", content: "3 Pcs", mrp: 0, price: 0 },
  { id: "standard-comets-5", categoryId: "standard-comets", name: "2 Comets 11 Variants", content: "1 Pcs", mrp: 0, price: 0 },
  { id: "standard-comets-6", categoryId: "standard-comets", name: "Pandav", content: "5 Pcs", mrp: 0, price: 0 },
  { id: "standard-comets-7", categoryId: "standard-comets", name: "3\" Comets 10 Variants", content: "1 Pcs", mrp: 0, price: 0 },
  { id: "standard-confetti-colour-smoke-1", categoryId: "standard-confetti-colour-smoke", name: "Color Fog Fountain", content: "5 Pcs", mrp: 0, price: 0 },
  { id: "standard-confetti-colour-smoke-2", categoryId: "standard-confetti-colour-smoke", name: "Rainbow Smoke", content: "2 Pcs", mrp: 0, price: 0 },
  { id: "standard-confetti-colour-smoke-3", categoryId: "standard-confetti-colour-smoke", name: "Magic Spray", content: "5 Pcs", mrp: 0, price: 0 },
  { id: "standard-confetti-colour-smoke-4", categoryId: "standard-confetti-colour-smoke", name: "Valentne's Day (16 Shot)", content: "1 Pcs", mrp: 0, price: 0 },
  { id: "standard-gift-box-1", categoryId: "standard-gift-box", name: "Gods Gift (25 Items)", content: "1 Pcs", mrp: 0, price: 0 },
  { id: "standard-gift-box-2", categoryId: "standard-gift-box", name: "Super (28 Items)", content: "1 Pcs", mrp: 0, price: 0 },
  { id: "standard-gift-box-3", categoryId: "standard-gift-box", name: "Great (31 Items)", content: "1 Pcs", mrp: 0, price: 0 },
  { id: "standard-gift-box-4", categoryId: "standard-gift-box", name: "Fantastic (37 Items)", content: "1 Pcs", mrp: 0, price: 0 },
  { id: "standard-gift-box-5", categoryId: "standard-gift-box", name: "Diamond (50 Items)", content: "1 Pcs", mrp: 0, price: 0 },
  { id: "standard-gift-box-6", categoryId: "standard-gift-box", name: "Titan (55 Items)", content: "1 Pcs", mrp: 0, price: 0 },
  { id: "standard-0-75-cakes-1", categoryId: "standard-0-75-cakes", name: "Blue Thunder (56 Shots)", content: "1 Pcs", mrp: 0, price: 0 },
  { id: "standard-0-75-cakes-2", categoryId: "standard-0-75-cakes", name: "Sun Flower (100 Shots)", content: "1 Pcs", mrp: 0, price: 0 },
  { id: "standard-0-75-cakes-3", categoryId: "standard-0-75-cakes", name: "Red Roses (125 Shots)", content: "1 Pcs", mrp: 0, price: 0 },
  { id: "standard-0-75-cakes-4", categoryId: "standard-0-75-cakes", name: "Speed (200 Shots)", content: "1 Pcs", mrp: 0, price: 0 },
  { id: "standard-0-75-cakes-5", categoryId: "standard-0-75-cakes", name: "Paradise (250 Shots)", content: "1 Pcs", mrp: 0, price: 0 },
  { id: "standard-0-75-cakes-6", categoryId: "standard-0-75-cakes", name: "Oh! Kolkata! (500 Shots)", content: "1 Pcs", mrp: 0, price: 0 },
  { id: "elite-sparklers-1", categoryId: "elite-sparklers", name: "15cm Electric", content: "10 Pcs", mrp: 0, price: 0 },
  { id: "elite-sparklers-2", categoryId: "elite-sparklers", name: "15cm Colour", content: "10 Pcs", mrp: 0, price: 0 },
  { id: "elite-sparklers-3", categoryId: "elite-sparklers", name: "15cm Green", content: "10 Pcs", mrp: 0, price: 0 },
  { id: "elite-sparklers-4", categoryId: "elite-sparklers", name: "15cm Red", content: "10 Pcs", mrp: 0, price: 0 },
  { id: "elite-sparklers-5", categoryId: "elite-sparklers", name: "30cm Electric", content: "5 Pcs", mrp: 0, price: 0 },
  { id: "elite-sparklers-6", categoryId: "elite-sparklers", name: "30cm Colour", content: "5 Pcs", mrp: 0, price: 0 },
  { id: "elite-sparklers-7", categoryId: "elite-sparklers", name: "50cm Electric", content: "5 Pcs", mrp: 0, price: 0 },
  { id: "elite-sparklers-8", categoryId: "elite-sparklers", name: "50cm Colour", content: "5 Pcs", mrp: 0, price: 0 },
  { id: "elite-flower-pot-1", categoryId: "elite-flower-pot", name: "Flower Pot Big", content: "10 Pcs", mrp: 0, price: 0 },
  { id: "elite-flower-pot-2", categoryId: "elite-flower-pot", name: "Flower Pot Special", content: "10 Pcs", mrp: 0, price: 0 },
  { id: "elite-flower-pot-3", categoryId: "elite-flower-pot", name: "Flower Pot Ashoka", content: "10 Pcs", mrp: 0, price: 0 },
  { id: "elite-flower-pot-4", categoryId: "elite-flower-pot", name: "Colour Koti", content: "10 Pcs", mrp: 0, price: 0 },
  { id: "elite-flower-pot-5", categoryId: "elite-flower-pot", name: "Tri Colour", content: "5 Pcs", mrp: 0, price: 0 },
  { id: "elite-ground-chakkar-1", categoryId: "elite-ground-chakkar", name: "Gc Special", content: "10 Pcs", mrp: 0, price: 0 },
  { id: "elite-ground-chakkar-2", categoryId: "elite-ground-chakkar", name: "Gc Deluxe Spinner", content: "10 Pcs", mrp: 0, price: 0 },
  { id: "elite-ground-chakkar-3", categoryId: "elite-ground-chakkar", name: "Disco Wheel", content: "5 Pcs", mrp: 0, price: 0 },
  { id: "elite-ground-chakkar-4", categoryId: "elite-ground-chakkar", name: "Gc Special Spinner", content: "10 Pcs", mrp: 0, price: 0 },
  { id: "elite-ground-chakkar-5", categoryId: "elite-ground-chakkar", name: "Wire Chakkar", content: "10 Pcs", mrp: 0, price: 0 },
  { id: "elite-twinking-star-1", categoryId: "elite-twinking-star", name: "1.5 Twinkling Star", content: "10 Pcs", mrp: 0, price: 0 },
  { id: "elite-twinking-star-2", categoryId: "elite-twinking-star", name: "4 Twinkling Star", content: "10 Pcs", mrp: 0, price: 0 },
  { id: "elite-one-sound-crackers-1", categoryId: "elite-one-sound-crackers", name: "2.75 Kuruvi", content: "5 Pcs", mrp: 0, price: 0 },
  { id: "elite-one-sound-crackers-2", categoryId: "elite-one-sound-crackers", name: "3.5 Lakshmi", content: "5 Pcs", mrp: 0, price: 0 },
  { id: "elite-one-sound-crackers-3", categoryId: "elite-one-sound-crackers", name: "4 Lakshmi", content: "5 Pcs", mrp: 0, price: 0 },
  { id: "elite-one-sound-crackers-4", categoryId: "elite-one-sound-crackers", name: "4 Dlx Lakshmi", content: "5 Pcs", mrp: 0, price: 0 },
  { id: "elite-one-sound-crackers-5", categoryId: "elite-one-sound-crackers", name: "4 Gold Lakshmi", content: "5 Pcs", mrp: 0, price: 0 },
  { id: "elite-one-sound-crackers-6", categoryId: "elite-one-sound-crackers", name: "5 Himalayan", content: "5 Pcs", mrp: 0, price: 0 },
  { id: "elite-one-sound-crackers-7", categoryId: "elite-one-sound-crackers", name: "2 Sound Crackers", content: "5 Pcs", mrp: 0, price: 0 },
  { id: "elite-one-sound-crackers-8", categoryId: "elite-one-sound-crackers", name: "Bijili 50pcs", content: "1 Bag", mrp: 0, price: 0 },
  { id: "elite-one-sound-crackers-9", categoryId: "elite-one-sound-crackers", name: "Bijili 100 Pcs", content: "1 Bag", mrp: 0, price: 0 },
  { id: "elite-bomb-1", categoryId: "elite-bomb", name: "Bullet Bomb", content: "10 Pcs", mrp: 0, price: 0 },
  { id: "elite-bomb-2", categoryId: "elite-bomb", name: "Classsic Bomb", content: "10 Pcs", mrp: 0, price: 0 },
  { id: "elite-bomb-3", categoryId: "elite-bomb", name: "Agni Bomb", content: "10 Pcs", mrp: 0, price: 0 },
  { id: "elite-bomb-4", categoryId: "elite-bomb", name: "Digital Bomb", content: "10 Pcs", mrp: 0, price: 0 },
  { id: "elite-paper-bomb-1", categoryId: "elite-paper-bomb", name: "250gm", content: "1 Pcs", mrp: 0, price: 0 },
  { id: "elite-paper-bomb-2", categoryId: "elite-paper-bomb", name: "500gm", content: "1 Pcs", mrp: 0, price: 0 },
  { id: "elite-paper-bomb-3", categoryId: "elite-paper-bomb", name: "1000gm", content: "1 Pcs", mrp: 0, price: 0 },
  { id: "elite-rocket-1", categoryId: "elite-rocket", name: "Rocket Bomb", content: "10 Pcs", mrp: 0, price: 0 },
  { id: "elite-rocket-2", categoryId: "elite-rocket", name: "Lunik Rocket", content: "10 Pcs", mrp: 0, price: 0 },
  { id: "elite-rocket-3", categoryId: "elite-rocket", name: "Whistling Rocket", content: "5 Pcs", mrp: 0, price: 0 },
  { id: "elite-night-fancy-1", categoryId: "elite-night-fancy", name: "Star Light", content: "5 Pcs", mrp: 0, price: 0 },
  { id: "elite-night-fancy-2", categoryId: "elite-night-fancy", name: "Golden Drops", content: "5 Pcs", mrp: 0, price: 0 },
  { id: "elite-night-fancy-3", categoryId: "elite-night-fancy", name: "Peacock Feather", content: "5 Pcs", mrp: 0, price: 0 },
  { id: "elite-night-fancy-4", categoryId: "elite-night-fancy", name: "Colour Rain", content: "5 Pcs", mrp: 0, price: 0 },
  { id: "elite-night-fancy-5", categoryId: "elite-night-fancy", name: "Tin", content: "1 Pcs", mrp: 0, price: 0 },
  { id: "elite-night-fancy-6", categoryId: "elite-night-fancy", name: "Selfie Stick", content: "5 Pcs", mrp: 0, price: 0 },
  { id: "elite-night-fancy-7", categoryId: "elite-night-fancy", name: "Butterfly", content: "10 Pcs", mrp: 0, price: 0 },
  { id: "elite-night-fancy-8", categoryId: "elite-night-fancy", name: "Bambaram", content: "10 Pcs", mrp: 0, price: 0 },
  { id: "elite-night-fancy-9", categoryId: "elite-night-fancy", name: "Photo Flash", content: "5 Pcs", mrp: 0, price: 0 },
  { id: "elite-night-fancy-10", categoryId: "elite-night-fancy", name: "Tin Fountain Celebrity", content: "1 Pcs", mrp: 0, price: 0 },
  { id: "elite-night-fancy-11", categoryId: "elite-night-fancy", name: "Tin Fountain", content: "1 Pcs", mrp: 0, price: 0 },
  { id: "elite-night-fancy-12", categoryId: "elite-night-fancy", name: "Money Bank", content: "3 Pcs", mrp: 0, price: 0 },
  { id: "elite-night-fancy-13", categoryId: "elite-night-fancy", name: "Kit Kat", content: "10 Pcs", mrp: 0, price: 0 },
  { id: "elite-night-fancy-14", categoryId: "elite-night-fancy", name: "Helicopter", content: "5 Pcs", mrp: 0, price: 0 },
  { id: "elite-night-fancy-15", categoryId: "elite-night-fancy", name: "Disco Shower", content: "5 Pcs", mrp: 0, price: 0 },
  { id: "elite-night-fancy-16", categoryId: "elite-night-fancy", name: "Black & White", content: "5 Pcs", mrp: 0, price: 0 },
  { id: "elite-night-fancy-17", categoryId: "elite-night-fancy", name: "Wowers", content: "5 Pcs", mrp: 0, price: 0 },
  { id: "elite-night-fancy-18", categoryId: "elite-night-fancy", name: "Cylinder Bomb", content: "1 Pcs", mrp: 0, price: 0 },
  { id: "elite-night-fancy-19", categoryId: "elite-night-fancy", name: "Siren Mini", content: "5 Pcs", mrp: 0, price: 0 },
  { id: "elite-night-fancy-20", categoryId: "elite-night-fancy", name: "Amman Full Crackling", content: "3 Pcs", mrp: 0, price: 0 },
  { id: "elite-night-fancy-21", categoryId: "elite-night-fancy", name: "Colour Changing Signal", content: "5 Pcs", mrp: 0, price: 0 },
  { id: "elite-night-fancy-22", categoryId: "elite-night-fancy", name: "Assorted Cartoon", content: "10 Pcs", mrp: 0, price: 0 },
  { id: "elite-night-fancy-23", categoryId: "elite-night-fancy", name: "Colour Smoke", content: "3 Pcs", mrp: 0, price: 0 },
  { id: "elite-peacock-1", categoryId: "elite-peacock", name: "Celebrity Peacock", content: "1 Pcs", mrp: 0, price: 0 },
  { id: "elite-peacock-2", categoryId: "elite-peacock", name: "Success Peacock", content: "1 Pcs", mrp: 0, price: 0 },
  { id: "elite-peacock-3", categoryId: "elite-peacock", name: "Bada Peacock", content: "1 Pcs", mrp: 0, price: 0 },
  { id: "elite-comets-1", categoryId: "elite-comets", name: "7 Shots", content: "5 Pcs", mrp: 0, price: 0 },
  { id: "elite-comets-2", categoryId: "elite-comets", name: "Sks", content: "10 Pcs", mrp: 0, price: 0 },
  { id: "elite-comets-3", categoryId: "elite-comets", name: "Chotta Fancy", content: "1 Pcs", mrp: 0, price: 0 },
  { id: "elite-comets-4", categoryId: "elite-comets", name: "2 Comets", content: "3 Pcs", mrp: 0, price: 0 },
  { id: "elite-comets-5", categoryId: "elite-comets", name: "3.5 Comets", content: "1 Pcs", mrp: 0, price: 0 },
  { id: "elite-comets-6", categoryId: "elite-comets", name: "3.5 Comets Ak", content: "1 Pcs", mrp: 0, price: 0 },
  { id: "elite-comets-7", categoryId: "elite-comets", name: "4.5 Pipe", content: "1 Pcs", mrp: 0, price: 0 },
  { id: "elite-comets-8", categoryId: "elite-comets", name: "4.5 Niagara", content: "1 Pcs", mrp: 0, price: 0 },
  { id: "elite-multi-shots-1", categoryId: "elite-multi-shots", name: "12 Rider", content: "1 Pcs", mrp: 0, price: 0 },
  { id: "elite-multi-shots-2", categoryId: "elite-multi-shots", name: "25 Rider", content: "1 Pcs", mrp: 0, price: 0 },
  { id: "elite-multi-shots-3", categoryId: "elite-multi-shots", name: "30 Shots", content: "1 Pcs", mrp: 0, price: 0 },
  { id: "elite-multi-shots-4", categoryId: "elite-multi-shots", name: "60 Shots", content: "1 Pcs", mrp: 0, price: 0 },
  { id: "elite-multi-shots-5", categoryId: "elite-multi-shots", name: "120 Shots", content: "1 Pcs", mrp: 0, price: 0 },
  { id: "elite-multi-shots-6", categoryId: "elite-multi-shots", name: "240 Shots", content: "1 Pcs", mrp: 0, price: 0 },
  { id: "elite-matches-1", categoryId: "elite-matches", name: "Royal Super Deluxe", content: "5OP", mrp: 0, price: 0 },
  { id: "elite-matches-2", categoryId: "elite-matches", name: "Lion Matches", content: "100 Pcs", mrp: 0, price: 0 },
  { id: "elite-matches-3", categoryId: "elite-matches", name: "Royal Matches", content: "100 Pcs", mrp: 0, price: 0 },
  { id: "elite-gift-box-1", categoryId: "elite-gift-box", name: "20 Items", content: "", mrp: 0, price: 0 },
  { id: "elite-gift-box-2", categoryId: "elite-gift-box", name: "30 Items", content: "", mrp: 0, price: 0 },
  { id: "elite-gift-box-3", categoryId: "elite-gift-box", name: "40 Items", content: "", mrp: 0, price: 0 },
  { id: "elite-gift-box-4", categoryId: "elite-gift-box", name: "50 Items", content: "", mrp: 0, price: 0 },
];
