// AUTO-GENERATED from "standard crackers price-list.pdf" (real 2025 values).
// Standard brand = 84% off MRP; Elite brand = 90% off MRP. Both stored explicitly.
// Seed for the D1 catalogue + fallback when the DB is empty.

export type SeedCategory = { id: string; line: "standard" | "elite"; name: string };
export type SeedProduct = {
  id: string; categoryId: string; name: string; content: string; mrp: number; price: number;
};

export const SEED_CATEGORIES: SeedCategory[] = [
  { id: "standard-sparklers", line: "standard", name: "Sparklers" },
  { id: "standard-chakkar", line: "standard", name: "Chakkar" },
  { id: "standard-flower-pot", line: "standard", name: "Flower Pot" },
  { id: "standard-twinkling-star", line: "standard", name: "Twinkling Star" },
  { id: "standard-rocket", line: "standard", name: "Rocket" },
  { id: "standard-bomb", line: "standard", name: "Bomb" },
  { id: "standard-sound-crackers", line: "standard", name: "Sound Crackers" },
  { id: "standard-fancy-fireworks", line: "standard", name: "Fancy Fireworks" },
  { id: "standard-sky-shot", line: "standard", name: "Sky Shot" },
  { id: "standard-multi-shot", line: "standard", name: "Multi Shot" },
  { id: "standard-giftbox", line: "standard", name: "Giftbox" },
  { id: "standard-special-attraction", line: "standard", name: "Special Attraction" },
  { id: "elite-sparklers", line: "elite", name: "Sparklers" },
  { id: "elite-chakkar", line: "elite", name: "Chakkar" },
  { id: "elite-flower-pot", line: "elite", name: "Flower Pot" },
  { id: "elite-twinkling-star", line: "elite", name: "Twinkling Star" },
  { id: "elite-rocket", line: "elite", name: "Rocket" },
  { id: "elite-bomb", line: "elite", name: "Bomb" },
  { id: "elite-sound-crackers", line: "elite", name: "Sound Crackers" },
  { id: "elite-fancy-fireworks", line: "elite", name: "Fancy Fireworks" },
  { id: "elite-sky", line: "elite", name: "Sky" },
  { id: "elite-multishot", line: "elite", name: "Multishot" },
  { id: "elite-giftbox", line: "elite", name: "Giftbox" },
];

export const SEED_PRODUCTS: SeedProduct[] = [
  { id: "standard-sparklers-1", categoryId: "standard-sparklers", name: "12 Cm Gold Sparklers", content: "12 CM · 1 Box", mrp: 331, price: 53 },
  { id: "standard-sparklers-2", categoryId: "standard-sparklers", name: "12 Cm Crackling Sparklers", content: "12 CM · 1 Box", mrp: 350, price: 56 },
  { id: "standard-sparklers-3", categoryId: "standard-sparklers", name: "12 Cm Red Color Sparklers", content: "12 CM · 1 Box", mrp: 331, price: 53 },
  { id: "standard-sparklers-4", categoryId: "standard-sparklers", name: "12 Cm Four Color Sparklers", content: "12 CM · 1 Box", mrp: 306, price: 49 },
  { id: "standard-sparklers-5", categoryId: "standard-sparklers", name: "15 Cm Std Gold Sparklers", content: "15 CM · 1 Box", mrp: 544, price: 87 },
  { id: "standard-sparklers-6", categoryId: "standard-sparklers", name: "15 Cm Std Red Color Sparklers", content: "15 CM · 1 Box", mrp: 513, price: 82 },
  { id: "standard-sparklers-7", categoryId: "standard-sparklers", name: "15 Cm Std Crackling Sparklers", content: "15 CM · 1 Box", mrp: 619, price: 99 },
  { id: "standard-sparklers-8", categoryId: "standard-sparklers", name: "15 Cm Lavender Sparklers", content: "15 CM · 1 Box", mrp: 644, price: 103 },
  { id: "standard-sparklers-9", categoryId: "standard-sparklers", name: "15 Cm Lemon Tree Sparklers", content: "15 CM · 1 Box", mrp: 500, price: 80 },
  { id: "standard-sparklers-10", categoryId: "standard-sparklers", name: "20 Cm Gold Sparklers", content: "20 CM · 1 Box", mrp: 500, price: 80 },
  { id: "standard-sparklers-11", categoryId: "standard-sparklers", name: "20 Cm Export Crackling", content: "20 CM · 1 Box", mrp: 581, price: 93 },
  { id: "standard-sparklers-12", categoryId: "standard-sparklers", name: "30 Cm Gold Sparklers", content: "30 CM · 1 Box", mrp: 550, price: 88 },
  { id: "standard-sparklers-13", categoryId: "standard-sparklers", name: "30 Cm Crackling Sparklers", content: "30 CM · 1 Box", mrp: 619, price: 99 },
  { id: "standard-chakkar-1", categoryId: "standard-chakkar", name: "Red And White", content: "10 PCS · 1 Box", mrp: 438, price: 70 },
  { id: "standard-chakkar-2", categoryId: "standard-chakkar", name: "Zamin Chakkar Ashoka", content: "10 PCS · 1 Box", mrp: 688, price: 110 },
  { id: "standard-chakkar-3", categoryId: "standard-chakkar", name: "Twin Spin Wheel", content: "5 PCS · 1 Box", mrp: 725, price: 116 },
  { id: "standard-chakkar-4", categoryId: "standard-chakkar", name: "Scarlet Saucer", content: "5 PCS · 1 Box", mrp: 725, price: 116 },
  { id: "standard-chakkar-5", categoryId: "standard-chakkar", name: "Chavi Zamin Chakkar Big", content: "25 PCS · 1 Box", mrp: 913, price: 146 },
  { id: "standard-chakkar-6", categoryId: "standard-chakkar", name: "Whizz Wheel", content: "10 PCS · 1 Box", mrp: 913, price: 146 },
  { id: "standard-chakkar-7", categoryId: "standard-chakkar", name: "Zamin Chakkars Special", content: "10 PCS · 1 Box", mrp: 1169, price: 187 },
  { id: "standard-chakkar-8", categoryId: "standard-chakkar", name: "Zamin Chakkar Deluxe", content: "10 PCS · 1 Box", mrp: 1500, price: 240 },
  { id: "standard-chakkar-9", categoryId: "standard-chakkar", name: "Zamin Chakkar Super Deluxe", content: "10 PCS · 1 Box", mrp: 1656, price: 265 },
  { id: "standard-chakkar-10", categoryId: "standard-chakkar", name: "Poker Wheel", content: "5 PCS · 1 Box", mrp: 2100, price: 336 },
  { id: "standard-chakkar-11", categoryId: "standard-chakkar", name: "Cuckoo Wheel", content: "5 PCS · 1 Box", mrp: 2100, price: 336 },
  { id: "standard-chakkar-12", categoryId: "standard-chakkar", name: "Doller Wheel", content: "5 PCS · 1 Box", mrp: 2100, price: 336 },
  { id: "standard-flower-pot-1", categoryId: "standard-flower-pot", name: "Mini Fountain Gold/Red", content: "5 PCS · 1 Box", mrp: 469, price: 75 },
  { id: "standard-flower-pot-2", categoryId: "standard-flower-pot", name: "Great Splendour", content: "1 PC · 1 Box", mrp: 538, price: 86 },
  { id: "standard-flower-pot-3", categoryId: "standard-flower-pot", name: "Jet Fountain", content: "5 PCS · 1 Box", mrp: 581, price: 93 },
  { id: "standard-flower-pot-4", categoryId: "standard-flower-pot", name: "Flowerpot Small", content: "10 PCS · 1 Box", mrp: 600, price: 96 },
  { id: "standard-flower-pot-5", categoryId: "standard-flower-pot", name: "Flowerpot Big", content: "10 PCS · 1 Box", mrp: 1038, price: 166 },
  { id: "standard-flower-pot-6", categoryId: "standard-flower-pot", name: "Flowerpot Special", content: "10 PCS · 1 Box", mrp: 1369, price: 219 },
  { id: "standard-flower-pot-7", categoryId: "standard-flower-pot", name: "Cheers", content: "3 PCS · 1 Box", mrp: 1456, price: 233 },
  { id: "standard-flower-pot-8", categoryId: "standard-flower-pot", name: "Flowerpot Delux", content: "10 PCS · 1 Box", mrp: 1844, price: 295 },
  { id: "standard-flower-pot-9", categoryId: "standard-flower-pot", name: "Jade Flower", content: "5 PCS · 1 Box", mrp: 2038, price: 326 },
  { id: "standard-flower-pot-10", categoryId: "standard-flower-pot", name: "Jewel Pots", content: "5 PCS · 1 Box", mrp: 2013, price: 322 },
  { id: "standard-flower-pot-11", categoryId: "standard-flower-pot", name: "Happiness", content: "5 PCS · 1 Box", mrp: 2081, price: 333 },
  { id: "standard-flower-pot-12", categoryId: "standard-flower-pot", name: "Sun Drops", content: "5 PCS · 1 Box", mrp: 2100, price: 336 },
  { id: "standard-flower-pot-13", categoryId: "standard-flower-pot", name: "Laser Show", content: "5 PCS · 1 Box", mrp: 2625, price: 420 },
  { id: "standard-flower-pot-14", categoryId: "standard-flower-pot", name: "Lavender Fountain", content: "3 PCS · 1 Box", mrp: 2706, price: 433 },
  { id: "standard-flower-pot-15", categoryId: "standard-flower-pot", name: "Flowerpot Giant", content: "10 PCS · 1 Box", mrp: 2869, price: 459 },
  { id: "standard-flower-pot-16", categoryId: "standard-flower-pot", name: "Tri Color Fountain", content: "5 PCS · 1 Box", mrp: 2913, price: 466 },
  { id: "standard-flower-pot-17", categoryId: "standard-flower-pot", name: "Colour Fountain", content: "4 PCS · 1 Box", mrp: 3075, price: 492 },
  { id: "standard-flower-pot-18", categoryId: "standard-flower-pot", name: "Crackling King", content: "5 PCS · 1 Box", mrp: 3119, price: 499 },
  { id: "standard-flower-pot-19", categoryId: "standard-flower-pot", name: "Tri Colour Millennium", content: "5 PCS · 1 Box", mrp: 3394, price: 543 },
  { id: "standard-flower-pot-20", categoryId: "standard-flower-pot", name: "Colour World", content: "10 PCS · 1 Box", mrp: 3469, price: 555 },
  { id: "standard-twinkling-star-1", categoryId: "standard-twinkling-star", name: "Twinkling Star 45 Cm", content: "10 PCS · 1 Box", mrp: 381, price: 61 },
  { id: "standard-twinkling-star-2", categoryId: "standard-twinkling-star", name: "Twinkling Star 60 Cm", content: "10 PCS · 1 Box", mrp: 550, price: 88 },
  { id: "standard-twinkling-star-3", categoryId: "standard-twinkling-star", name: "Multi Colour Candle", content: "10 PCS · 1 Box", mrp: 756, price: 121 },
  { id: "standard-rocket-1", categoryId: "standard-rocket", name: "Rainbow Rocket", content: "10 PCS · 1 Box", mrp: 1013, price: 162 },
  { id: "standard-rocket-2", categoryId: "standard-rocket", name: "Bomb Rocket", content: "10 PCS · 1 Box", mrp: 1094, price: 175 },
  { id: "standard-rocket-3", categoryId: "standard-rocket", name: "Rohini Rocket", content: "10 PCS · 1 Box", mrp: 1769, price: 283 },
  { id: "standard-bomb-1", categoryId: "standard-bomb", name: "Color Flash (Holi Special)", content: "5 PCS · 1 Box", mrp: 675, price: 108 },
  { id: "standard-bomb-2", categoryId: "standard-bomb", name: "Hydrogen Green", content: "10 PCS · 1 Box", mrp: 700, price: 112 },
  { id: "standard-bomb-3", categoryId: "standard-bomb", name: "Standard Atom Bomb", content: "10 PCS · 1 Box", mrp: 781, price: 125 },
  { id: "standard-bomb-4", categoryId: "standard-bomb", name: "Thunder Bomb Green", content: "10 PCS · 1 Box", mrp: 1000, price: 160 },
  { id: "standard-sound-crackers-1", categoryId: "standard-sound-crackers", name: "Sparrow", content: "5 PCS · 1 Pkt", mrp: 113, price: 18 },
  { id: "standard-sound-crackers-2", categoryId: "standard-sound-crackers", name: "9 Cm Laxmi", content: "5 PCS · 1 Pkt", mrp: 175, price: 28 },
  { id: "standard-sound-crackers-3", categoryId: "standard-sound-crackers", name: "10 Cm Laxmi", content: "5 PCS · 1 Pkt", mrp: 250, price: 40 },
  { id: "standard-sound-crackers-4", categoryId: "standard-sound-crackers", name: "Two Sound", content: "5 PCS · 1 Pkt", mrp: 269, price: 43 },
  { id: "standard-sound-crackers-5", categoryId: "standard-sound-crackers", name: "Red Bijili", content: "100 PCS · 1 Bag", mrp: 450, price: 72 },
  { id: "standard-sound-crackers-6", categoryId: "standard-sound-crackers", name: "Striped Bijili", content: "100 PCS · 1 Bag", mrp: 375, price: 60 },
  { id: "standard-sound-crackers-7", categoryId: "standard-sound-crackers", name: "\"28\" Magic Crackers", content: "1 PC · 1 Pkt", mrp: 219, price: 35 },
  { id: "standard-sound-crackers-8", categoryId: "standard-sound-crackers", name: "\"56\" Magic Crackers", content: "1 PC · 1 Pkt", mrp: 375, price: 60 },
  { id: "standard-sound-crackers-9", categoryId: "standard-sound-crackers", name: "\"100\" Magic Crackers", content: "1 PC · 1 Pkt", mrp: 694, price: 111 },
  { id: "standard-sound-crackers-10", categoryId: "standard-sound-crackers", name: "\"1000\" Magic Crackers", content: "1 STRING · 1 Box", mrp: 3444, price: 551 },
  { id: "standard-sound-crackers-11", categoryId: "standard-sound-crackers", name: "\"2000\" Magic Crackers", content: "1 STRING · 1 Box", mrp: 6669, price: 1067 },
  { id: "standard-sound-crackers-12", categoryId: "standard-sound-crackers", name: "\"5000\" Magic Crackers", content: "1 STRING · 1 Box", mrp: 15419, price: 2467 },
  { id: "standard-sound-crackers-13", categoryId: "standard-sound-crackers", name: "\"10000\" Magic Crackers", content: "1 STRING · 1 Box", mrp: 30831, price: 4933 },
  { id: "standard-fancy-fireworks-1", categoryId: "standard-fancy-fireworks", name: "Chat Chat", content: "10 PCS · 1 Box", mrp: 525, price: 84 },
  { id: "standard-fancy-fireworks-2", categoryId: "standard-fancy-fireworks", name: "Assorted Cartoon", content: "10 PCS · 1 Box", mrp: 613, price: 98 },
  { id: "standard-fancy-fireworks-3", categoryId: "standard-fancy-fireworks", name: "Disco Flash", content: "6 PCS · 1 Box", mrp: 638, price: 102 },
  { id: "standard-fancy-fireworks-4", categoryId: "standard-fancy-fireworks", name: "Magic Whip", content: "1 PC · 1 Box", mrp: 681, price: 109 },
  { id: "standard-fancy-fireworks-5", categoryId: "standard-fancy-fireworks", name: "Signal Light", content: "5 PCS · 1 Box", mrp: 806, price: 129 },
  { id: "standard-fancy-fireworks-6", categoryId: "standard-fancy-fireworks", name: "Triple Guns", content: "5 PCS · 1 Box", mrp: 906, price: 145 },
  { id: "standard-fancy-fireworks-7", categoryId: "standard-fancy-fireworks", name: "Color Bust", content: "10 PCS · 1 Box", mrp: 1106, price: 177 },
  { id: "standard-fancy-fireworks-8", categoryId: "standard-fancy-fireworks", name: "Golden Whistle", content: "5 PCS · 1 Box", mrp: 1319, price: 211 },
  { id: "standard-fancy-fireworks-9", categoryId: "standard-fancy-fireworks", name: "Mine Of Crackers", content: "5 PCS · 1 Box", mrp: 1363, price: 218 },
  { id: "standard-fancy-fireworks-10", categoryId: "standard-fancy-fireworks", name: "Rainbow Fog (2 Pcs)", content: "2 PCS · 1 Box", mrp: 1531, price: 245 },
  { id: "standard-fancy-fireworks-11", categoryId: "standard-fancy-fireworks", name: "Colour Changing Butterfly", content: "10 PCS · 1 Box", mrp: 1581, price: 253 },
  { id: "standard-fancy-fireworks-12", categoryId: "standard-fancy-fireworks", name: "Meteors", content: "5 PCS · 1 Box", mrp: 2063, price: 330 },
  { id: "standard-fancy-fireworks-13", categoryId: "standard-fancy-fireworks", name: "Gold Rush", content: "5 PCS · 1 Box", mrp: 2238, price: 358 },
  { id: "standard-fancy-fireworks-14", categoryId: "standard-fancy-fireworks", name: "Swastik Wheel", content: "5 PCS · 1 Box", mrp: 2156, price: 345 },
  { id: "standard-fancy-fireworks-15", categoryId: "standard-fancy-fireworks", name: "Aerial Out", content: "5 PCS · 1 Box", mrp: 2300, price: 368 },
  { id: "standard-fancy-fireworks-16", categoryId: "standard-fancy-fireworks", name: "Golden Drops", content: "5 PCS · 1 Box", mrp: 2769, price: 443 },
  { id: "standard-sky-shot-1", categoryId: "standard-sky-shot", name: "1 ¼ Inch Star Fire", content: "1 PC · 1 Box", mrp: 606, price: 97 },
  { id: "standard-sky-shot-2", categoryId: "standard-sky-shot", name: "1 ¾ Inch Jasmine Drops", content: "3 PCS · 1 Box", mrp: 3731, price: 597 },
  { id: "standard-sky-shot-3", categoryId: "standard-sky-shot", name: "1 ¾ Inch Color Thunder Bolt", content: "3 PCS · 1 Box", mrp: 3731, price: 597 },
  { id: "standard-sky-shot-4", categoryId: "standard-sky-shot", name: "2” Spring Willow (14 Varients)", content: "1 PC · 1 Box", mrp: 1475, price: 236 },
  { id: "standard-sky-shot-5", categoryId: "standard-sky-shot", name: "3” Kerala Beauty (30 Varients)", content: "1 PC · 1 Box", mrp: 2694, price: 431 },
  { id: "standard-multi-shot-1", categoryId: "standard-multi-shot", name: "12 SHOT (FLIPPER, WABOT, etc.)", content: "1 PC · 1 Box", mrp: 1363, price: 218 },
  { id: "standard-multi-shot-2", categoryId: "standard-multi-shot", name: "20 Shot (8 Varients)", content: "1 PC · 1 Box", mrp: 4775, price: 764 },
  { id: "standard-multi-shot-3", categoryId: "standard-multi-shot", name: "25 Shots (Rover, Rms, Jem)", content: "1 PC · 1 Box", mrp: 5038, price: 806 },
  { id: "standard-multi-shot-4", categoryId: "standard-multi-shot", name: "30 Shot (3 Varients)", content: "1 PC · 1 Box", mrp: 5469, price: 875 },
  { id: "standard-multi-shot-5", categoryId: "standard-multi-shot", name: "40 Shots (Kibo, Black Ghost)", content: "1 PC · 1 Box", mrp: 6944, price: 1111 },
  { id: "standard-multi-shot-6", categoryId: "standard-multi-shot", name: "60 Shots (Clipper, Trilo, Aibo)", content: "1 PC · 1 Box", mrp: 9113, price: 1458 },
  { id: "standard-multi-shot-7", categoryId: "standard-multi-shot", name: "100 Shots (Eat, Matrix,", content: "1 PC · 1 Box", mrp: 13269, price: 2123 },
  { id: "standard-multi-shot-8", categoryId: "standard-multi-shot", name: "120 SHOT (ROBO, RIX,SAFFIRE, etc)", content: "1 PC · 1 Box", mrp: 15481, price: 2477 },
  { id: "standard-multi-shot-9", categoryId: "standard-multi-shot", name: "240 SHOT - Rainbow Dance", content: "1 PC · 1 Box", mrp: 38450, price: 6152 },
  { id: "standard-giftbox-1", categoryId: "standard-giftbox", name: "Gift Box- \"Gods Gift\"", content: "25 ITEMS · 1 BOX", mrp: 5163, price: 826 },
  { id: "standard-giftbox-2", categoryId: "standard-giftbox", name: "Gift Box- \"Super\"", content: "28 ITEMS · 1 BOX", mrp: 5588, price: 894 },
  { id: "standard-giftbox-3", categoryId: "standard-giftbox", name: "Gift Box-\" Great\"", content: "31 ITEMS · 1 BOX", mrp: 6881, price: 1101 },
  { id: "standard-giftbox-4", categoryId: "standard-giftbox", name: "Gift Box- \"Wonderful\"", content: "34 ITEMS · 1 BOX", mrp: 8169, price: 1307 },
  { id: "standard-giftbox-5", categoryId: "standard-giftbox", name: "Gift Box- \"Fantastic\"", content: "37 ITEMS · 1 BOX", mrp: 9463, price: 1514 },
  { id: "standard-giftbox-6", categoryId: "standard-giftbox", name: "Gift Box- \"Khushi\"", content: "42 ITEMS · 1 BOX", mrp: 11181, price: 1789 },
  { id: "standard-giftbox-7", categoryId: "standard-giftbox", name: "Gift Box-\"Diamond\"", content: "50 ITEMS · 1 BOX", mrp: 14188, price: 2270 },
  { id: "standard-giftbox-8", categoryId: "standard-giftbox", name: "Gift Box- \"Titan\"", content: "55 ITEMS · 1 BOX", mrp: 16769, price: 2683 },
  { id: "standard-special-attraction-1", categoryId: "standard-special-attraction", name: "Pandav", content: "5 PCS · 1 BOX", mrp: 969, price: 155 },
  { id: "standard-special-attraction-2", categoryId: "standard-special-attraction", name: "Friendly Fire", content: "1 PC · 1 BOX", mrp: 938, price: 150 },
  { id: "standard-special-attraction-3", categoryId: "standard-special-attraction", name: "Team Captain", content: "1 PC · 1 BOX", mrp: 1125, price: 180 },
  { id: "standard-special-attraction-4", categoryId: "standard-special-attraction", name: "Avengers Special", content: "1 PC · 1 BOX", mrp: 781, price: 125 },
  { id: "standard-special-attraction-5", categoryId: "standard-special-attraction", name: "Peony", content: "1 PC · 1 BOX", mrp: 875, price: 140 },
  { id: "standard-special-attraction-6", categoryId: "standard-special-attraction", name: "Rainbow Fog", content: "5 PCS · 1 BOX", mrp: 3625, price: 580 },
  { id: "standard-special-attraction-7", categoryId: "standard-special-attraction", name: "Confetti", content: "2 PCS · 1 BOX", mrp: 1969, price: 315 },
  { id: "standard-special-attraction-8", categoryId: "standard-special-attraction", name: "Happy Spray Cannon", content: "2 PCS · 1 BOX", mrp: 2688, price: 430 },
  { id: "standard-special-attraction-9", categoryId: "standard-special-attraction", name: "Magic Spray", content: "5 PCS · 1 BOX", mrp: 1375, price: 220 },
  { id: "standard-special-attraction-10", categoryId: "standard-special-attraction", name: "Krack Jack", content: "3 PCS · 1 BOX", mrp: 3156, price: 505 },
  { id: "standard-special-attraction-11", categoryId: "standard-special-attraction", name: "Tug Of War", content: "5 PCS · 1 BOX", mrp: 906, price: 145 },
  { id: "standard-special-attraction-12", categoryId: "standard-special-attraction", name: "Cuckoo", content: "5 PCS · 1 BOX", mrp: 2094, price: 335 },
  { id: "standard-special-attraction-13", categoryId: "standard-special-attraction", name: "Jill Junk Juk", content: "3 PCS · 1 BOX", mrp: 2125, price: 340 },
  { id: "standard-special-attraction-14", categoryId: "standard-special-attraction", name: "Five Star", content: "5 PCS · 1 BOX", mrp: 1531, price: 245 },
  { id: "standard-special-attraction-15", categoryId: "standard-special-attraction", name: "Crackling Candy", content: "2 PCS · 1 BOX", mrp: 2094, price: 335 },
  { id: "standard-special-attraction-16", categoryId: "standard-special-attraction", name: "Magical Wand", content: "2 PCS · 1 BOX", mrp: 2094, price: 335 },
  { id: "standard-special-attraction-17", categoryId: "standard-special-attraction", name: "Pop Corn", content: "5 PCS · 1 BOX", mrp: 2344, price: 375 },
  { id: "standard-special-attraction-18", categoryId: "standard-special-attraction", name: "Sun Drops", content: "5 PCS · 1 BOX", mrp: 2094, price: 335 },
  { id: "standard-special-attraction-19", categoryId: "standard-special-attraction", name: "Money Penny", content: "5 PCS · 1 BOX", mrp: 2094, price: 335 },
  { id: "standard-special-attraction-20", categoryId: "standard-special-attraction", name: "Olympic Torch", content: "1 PC · 1 BOX", mrp: 2406, price: 385 },
  { id: "standard-special-attraction-21", categoryId: "standard-special-attraction", name: "Vibgyor", content: "1 PC · 1 BOX", mrp: 3219, price: 515 },
  { id: "standard-special-attraction-22", categoryId: "standard-special-attraction", name: "Little Dragon", content: "5 PC · 1 BOX", mrp: 2094, price: 335 },
  { id: "standard-special-attraction-23", categoryId: "standard-special-attraction", name: "Little Flower", content: "1 PC · 1 BOX", mrp: 469, price: 75 },
  { id: "standard-special-attraction-24", categoryId: "standard-special-attraction", name: "Jet Fountain", content: "10 PCS · 1 BOX", mrp: 1250, price: 200 },
  { id: "standard-special-attraction-25", categoryId: "standard-special-attraction", name: "120 Cm Silver Twinkling Deluxe", content: "10 PCS · 1 BOX", mrp: 1156, price: 185 },
  { id: "standard-special-attraction-26", categoryId: "standard-special-attraction", name: "Magnetic Torches", content: "10 PCS · 1 BOX", mrp: 469, price: 75 },
  { id: "standard-special-attraction-27", categoryId: "standard-special-attraction", name: "Fire Pencils", content: "10 PCS · 1 BOX", mrp: 469, price: 75 },
  { id: "standard-special-attraction-28", categoryId: "standard-special-attraction", name: "Four Colour Torches", content: "10 PCS · 1 BOX", mrp: 1313, price: 210 },
  { id: "elite-sparklers-1", categoryId: "elite-sparklers", name: "12Cm Eletcric Sparklers", content: "10 PCS · 1 Box", mrp: 250, price: 25 },
  { id: "elite-sparklers-2", categoryId: "elite-sparklers", name: "12Cm Crackling Sparklers", content: "10 PCS · 1 Box", mrp: 300, price: 30 },
  { id: "elite-sparklers-3", categoryId: "elite-sparklers", name: "12 Cm Red Sparklers", content: "10 PCS · 1 Box", mrp: 300, price: 30 },
  { id: "elite-sparklers-4", categoryId: "elite-sparklers", name: "12 Cm Green Sparklers", content: "10 PCS · 1 Box", mrp: 300, price: 30 },
  { id: "elite-sparklers-5", categoryId: "elite-sparklers", name: "15Cm Eletcric Sparklers", content: "10 PCS · 1 Box", mrp: 450, price: 45 },
  { id: "elite-sparklers-6", categoryId: "elite-sparklers", name: "15Cm Crackling Sparklers", content: "10 PCS · 1 Box", mrp: 500, price: 50 },
  { id: "elite-sparklers-7", categoryId: "elite-sparklers", name: "15 Cm Red Sparklers", content: "10 PCS · 1 Box", mrp: 550, price: 55 },
  { id: "elite-sparklers-8", categoryId: "elite-sparklers", name: "15 Cm Green Sparklers", content: "10 PCS · 1 Box", mrp: 600, price: 60 },
  { id: "elite-sparklers-9", categoryId: "elite-sparklers", name: "30 Cm Eletcric Sparklers", content: "5 PCS · 1 Box", mrp: 450, price: 45 },
  { id: "elite-sparklers-10", categoryId: "elite-sparklers", name: "30 Cm Crackling Sparklers", content: "5 PCS · 1 Box", mrp: 500, price: 50 },
  { id: "elite-sparklers-11", categoryId: "elite-sparklers", name: "50 Cm Eletcric Sparklers", content: "5 PCS · 1 Box", mrp: 1800, price: 180 },
  { id: "elite-sparklers-12", categoryId: "elite-sparklers", name: "50 Cm Crackling Sparklers", content: "5 PCS · 1 Box", mrp: 2000, price: 200 },
  { id: "elite-chakkar-1", categoryId: "elite-chakkar", name: "Ground Chakker Big", content: "10 PCS · 1 Box", mrp: 400, price: 40 },
  { id: "elite-chakkar-2", categoryId: "elite-chakkar", name: "Ground Chakker Asoka", content: "10 PCS · 1 Box", mrp: 550, price: 55 },
  { id: "elite-chakkar-3", categoryId: "elite-chakkar", name: "Ground Chakker Special", content: "10 PCS · 1 Box", mrp: 1000, price: 100 },
  { id: "elite-chakkar-4", categoryId: "elite-chakkar", name: "Ground Chakker Big", content: "25 PCS · 1 Box", mrp: 800, price: 80 },
  { id: "elite-chakkar-5", categoryId: "elite-chakkar", name: "Win Wheel Nano", content: "10 PCS · 1 Box", mrp: 900, price: 90 },
  { id: "elite-chakkar-6", categoryId: "elite-chakkar", name: "Ground Chakker Dlx", content: "10 PCS · 1 Box", mrp: 1400, price: 140 },
  { id: "elite-chakkar-7", categoryId: "elite-chakkar", name: "Win Wheel Mini", content: "10 PCS · 1 Box", mrp: 1500, price: 150 },
  { id: "elite-chakkar-8", categoryId: "elite-chakkar", name: "Wire Chakkers", content: "10 PCS · 1 Box", mrp: 1500, price: 150 },
  { id: "elite-chakkar-9", categoryId: "elite-chakkar", name: "Win Wheel Max", content: "10 PCS · 1 Box", mrp: 2000, price: 200 },
  { id: "elite-flower-pot-1", categoryId: "elite-flower-pot", name: "Flower Pots Small", content: "10 PCS · 1 Box", mrp: 600, price: 60 },
  { id: "elite-flower-pot-2", categoryId: "elite-flower-pot", name: "Flower Pots Big", content: "10 PCS · 1 Box", mrp: 1100, price: 110 },
  { id: "elite-flower-pot-3", categoryId: "elite-flower-pot", name: "Flower Pots Special", content: "10 PCS · 1 Box", mrp: 1200, price: 120 },
  { id: "elite-flower-pot-4", categoryId: "elite-flower-pot", name: "Flower Pots Asoka", content: "10 PCS · 1 Box", mrp: 1800, price: 180 },
  { id: "elite-flower-pot-5", categoryId: "elite-flower-pot", name: "Flower Pots Gaint", content: "10 PCS · 1 Box", mrp: 2500, price: 250 },
  { id: "elite-flower-pot-6", categoryId: "elite-flower-pot", name: "Flower Pots Delux", content: "10 PCS · 1 Box", mrp: 3000, price: 300 },
  { id: "elite-flower-pot-7", categoryId: "elite-flower-pot", name: "Tricolor Fountain", content: "10 PCS · 1 Box", mrp: 2500, price: 250 },
  { id: "elite-flower-pot-8", categoryId: "elite-flower-pot", name: "Colour Koti", content: "10 PCS · 1 Box", mrp: 3000, price: 300 },
  { id: "elite-flower-pot-9", categoryId: "elite-flower-pot", name: "Colour Koti Delux", content: "10 PCS · 1 Box", mrp: 3500, price: 350 },
  { id: "elite-flower-pot-10", categoryId: "elite-flower-pot", name: "Colour Koti Delux (Pink)", content: "10 PCS · 1 Box", mrp: 4000, price: 400 },
  { id: "elite-twinkling-star-1", categoryId: "elite-twinkling-star", name: "Twinkling Star 45 Cm", content: "10 PCS · 1 Box", mrp: 300, price: 30 },
  { id: "elite-twinkling-star-2", categoryId: "elite-twinkling-star", name: "Twinkling Star 120 Cm", content: "10 PCS · 1 Box", mrp: 900, price: 90 },
  { id: "elite-twinkling-star-3", categoryId: "elite-twinkling-star", name: "Ultra Color Pencil", content: "3 PCS · 1 Box", mrp: 900, price: 90 },
  { id: "elite-rocket-1", categoryId: "elite-rocket", name: "Color Rocket", content: "10 PCS · 1 Box", mrp: 1500, price: 150 },
  { id: "elite-rocket-2", categoryId: "elite-rocket", name: "Bomb Rocket", content: "10 PCS · 1 Box", mrp: 1500, price: 150 },
  { id: "elite-rocket-3", categoryId: "elite-rocket", name: "Lunik Rocket", content: "10 PCS · 1 Box", mrp: 1500, price: 150 },
  { id: "elite-rocket-4", categoryId: "elite-rocket", name: "Musical Rocket", content: "10 PCS · 1 Box", mrp: 1500, price: 150 },
  { id: "elite-bomb-1", categoryId: "elite-bomb", name: "Nova Bomb", content: "10 PCS · 1 Box", mrp: 800, price: 80 },
  { id: "elite-bomb-2", categoryId: "elite-bomb", name: "Hydro Bomb Green", content: "10 PCS · 1 Box", mrp: 1000, price: 100 },
  { id: "elite-bomb-3", categoryId: "elite-bomb", name: "Classic Bomb", content: "10 PCS · 1 Box", mrp: 1500, price: 150 },
  { id: "elite-bomb-4", categoryId: "elite-bomb", name: "Agni Bomb", content: "10 PCS · 1 Box", mrp: 2000, price: 200 },
  { id: "elite-bomb-5", categoryId: "elite-bomb", name: "Digital Bomb", content: "10 PCS · 1 Box", mrp: 2500, price: 250 },
  { id: "elite-sound-crackers-1", categoryId: "elite-sound-crackers", name: "2 3/4 Kuruvi", content: "5 PCS · 1 PKT", mrp: 100, price: 10 },
  { id: "elite-sound-crackers-2", categoryId: "elite-sound-crackers", name: "3 1/2 Lakxmi", content: "5 PCS · 1 PKT", mrp: 200, price: 20 },
  { id: "elite-sound-crackers-3", categoryId: "elite-sound-crackers", name: "4” Laxmi", content: "5 PCS · 1 PKT", mrp: 250, price: 25 },
  { id: "elite-sound-crackers-4", categoryId: "elite-sound-crackers", name: "4” Laxmi Dlx", content: "5 PCS · 1 PKT", mrp: 350, price: 35 },
  { id: "elite-sound-crackers-5", categoryId: "elite-sound-crackers", name: "Two Sounds", content: "5 PCS · 1 PKT", mrp: 350, price: 35 },
  { id: "elite-sound-crackers-6", categoryId: "elite-sound-crackers", name: "Red Bijilli", content: "100 PCS · 1 BAG", mrp: 400, price: 40 },
  { id: "elite-sound-crackers-7", categoryId: "elite-sound-crackers", name: "Stripped Bijilli", content: "100 PCS · 1 BAG", mrp: 500, price: 50 },
  { id: "elite-sound-crackers-8", categoryId: "elite-sound-crackers", name: "100 Wala Crackers", content: "1 PCS · 1 Box", mrp: 800, price: 80 },
  { id: "elite-sound-crackers-9", categoryId: "elite-sound-crackers", name: "1000 Wala Crackers", content: "1 PCS · 1 Box", mrp: 3000, price: 300 },
  { id: "elite-sound-crackers-10", categoryId: "elite-sound-crackers", name: "1000 Wala Crackers (Premium)", content: "1 PCS · 1 Box", mrp: 4000, price: 400 },
  { id: "elite-sound-crackers-11", categoryId: "elite-sound-crackers", name: "2000 Wala Crackers", content: "1 PCS · 1 Box", mrp: 6000, price: 600 },
  { id: "elite-sound-crackers-12", categoryId: "elite-sound-crackers", name: "2000 Wala Crackers (Premium)", content: "1 PCS · 1 Box", mrp: 8400, price: 840 },
  { id: "elite-sound-crackers-13", categoryId: "elite-sound-crackers", name: "5000 Wala Crackers", content: "1 PCS · 1 Box", mrp: 15000, price: 1500 },
  { id: "elite-sound-crackers-14", categoryId: "elite-sound-crackers", name: "5000 Wala Crackers (Premium)", content: "1 PCS · 1 Box", mrp: 21000, price: 2100 },
  { id: "elite-sound-crackers-15", categoryId: "elite-sound-crackers", name: "10000 Wala Crackers", content: "1 PCS · 1 Box", mrp: 30000, price: 3000 },
  { id: "elite-sound-crackers-16", categoryId: "elite-sound-crackers", name: "10000 Wala Crackers (Premium)", content: "1 PCS · 1 Box", mrp: 42000, price: 4200 },
  { id: "elite-fancy-fireworks-1", categoryId: "elite-fancy-fireworks", name: "Kit Kat", content: "5 PCS · 1 Box", mrp: 450, price: 45 },
  { id: "elite-fancy-fireworks-2", categoryId: "elite-fancy-fireworks", name: "Helicopter", content: "5 PCS · 1 Box", mrp: 1000, price: 100 },
  { id: "elite-fancy-fireworks-3", categoryId: "elite-fancy-fireworks", name: "Photo Flash", content: "5 PCS · 1 Box", mrp: 1000, price: 100 },
  { id: "elite-fancy-fireworks-4", categoryId: "elite-fancy-fireworks", name: "Tin", content: "1 PCS · 1 Box", mrp: 1000, price: 100 },
  { id: "elite-fancy-fireworks-5", categoryId: "elite-fancy-fireworks", name: "Golden Drops", content: "5 PCS · 1 Box", mrp: 1300, price: 130 },
  { id: "elite-fancy-fireworks-6", categoryId: "elite-fancy-fireworks", name: "Color Rain", content: "5 PCS · 1 Box", mrp: 1300, price: 130 },
  { id: "elite-fancy-fireworks-7", categoryId: "elite-fancy-fireworks", name: "Selfie Stick", content: "3 PCS · 1 Box", mrp: 1300, price: 130 },
  { id: "elite-fancy-fireworks-8", categoryId: "elite-fancy-fireworks", name: "5 Star Yellow (Shower)", content: "5 PCS · 1 Box", mrp: 1300, price: 130 },
  { id: "elite-fancy-fireworks-9", categoryId: "elite-fancy-fireworks", name: "Pop Corn Spiderman", content: "5 PCS · 1 Box", mrp: 1300, price: 130 },
  { id: "elite-fancy-fireworks-10", categoryId: "elite-fancy-fireworks", name: "Mily Bar White (Shower)", content: "5 PCS · 1 Box", mrp: 1350, price: 135 },
  { id: "elite-fancy-fireworks-11", categoryId: "elite-fancy-fireworks", name: "Jet Raider", content: "5 PCS · 1 Box", mrp: 1350, price: 135 },
  { id: "elite-fancy-fireworks-12", categoryId: "elite-fancy-fireworks", name: "Pogo", content: "5 PCS · 1 Box", mrp: 1400, price: 140 },
  { id: "elite-fancy-fireworks-13", categoryId: "elite-fancy-fireworks", name: "Kit Kat Red (Shower)", content: "5 PCS · 1 Box", mrp: 1400, price: 140 },
  { id: "elite-fancy-fireworks-14", categoryId: "elite-fancy-fireworks", name: "Water Queen", content: "1 PCS · 1 Box", mrp: 1500, price: 150 },
  { id: "elite-fancy-fireworks-15", categoryId: "elite-fancy-fireworks", name: "Shower", content: "5 PCS · 1 Box", mrp: 1500, price: 150 },
  { id: "elite-fancy-fireworks-16", categoryId: "elite-fancy-fireworks", name: "Sky Chutti", content: "5 PCS · 1 Box", mrp: 1500, price: 150 },
  { id: "elite-fancy-fireworks-17", categoryId: "elite-fancy-fireworks", name: "Spice Crackling", content: "5 PCS · 1 Box", mrp: 1500, price: 150 },
  { id: "elite-fancy-fireworks-18", categoryId: "elite-fancy-fireworks", name: "Color Jelly", content: "5 PCS · 1 Box", mrp: 1500, price: 150 },
  { id: "elite-fancy-fireworks-19", categoryId: "elite-fancy-fireworks", name: "Multi Coclor Peacock", content: "1 PCS · 1 Box", mrp: 2000, price: 200 },
  { id: "elite-fancy-fireworks-20", categoryId: "elite-fancy-fireworks", name: "Color Smoke", content: "5 PCS · 1 Box", mrp: 2000, price: 200 },
  { id: "elite-sky-1", categoryId: "elite-sky", name: "1” Chotta Shot (6 Varients)", content: "1 PCS · 1 Box", mrp: 400, price: 40 },
  { id: "elite-sky-2", categoryId: "elite-sky", name: "2” Sky Shot (12 Varients)", content: "1 PCS · 1 Box", mrp: 1200, price: 120 },
  { id: "elite-sky-3", categoryId: "elite-sky", name: "2.5” Sky Shot (6 Varients)", content: "1 PCS · 1 Box", mrp: 1800, price: 180 },
  { id: "elite-sky-4", categoryId: "elite-sky", name: "2.5” Sky Shot (6 Varients) – Dopuble Ball", content: "1 PCS · 1 Box", mrp: 2000, price: 200 },
  { id: "elite-sky-5", categoryId: "elite-sky", name: "2.5” Premium Sky Shot (14 Varients)", content: "1 PCS · 1 Box", mrp: 2200, price: 220 },
  { id: "elite-sky-6", categoryId: "elite-sky", name: "2.5” Sky Shot (3 Varients)", content: "3 PCS · 1 Box", mrp: 2500, price: 250 },
  { id: "elite-sky-7", categoryId: "elite-sky", name: "3” Sky Shot (Double Ball) (3 Varients)", content: "1 PCS · 1 Box", mrp: 3200, price: 320 },
  { id: "elite-sky-8", categoryId: "elite-sky", name: "4” Premium Sky Shot (4 Varients)", content: "1 PCS · 1 Box", mrp: 5500, price: 550 },
  { id: "elite-sky-9", categoryId: "elite-sky", name: "4” Sky Shot (7 Step)", content: "1 PCS · 1 Box", mrp: 4000, price: 400 },
  { id: "elite-sky-10", categoryId: "elite-sky", name: "4” Sky Shot (Double Ball) (3 Varients)", content: "1 PCS · 1 Box", mrp: 4500, price: 450 },
  { id: "elite-sky-11", categoryId: "elite-sky", name: "4” Premium Sky Shot (Nayagara)", content: "1 PCS · 1 Box", mrp: 4750, price: 475 },
  { id: "elite-sky-12", categoryId: "elite-sky", name: "4” Premium Sky Shot (Texas)", content: "1 PCS · 1 Box", mrp: 4750, price: 475 },
  { id: "elite-sky-13", categoryId: "elite-sky", name: "4” Premium Sky Shot (Lemon)", content: "1 PCS · 1 Box", mrp: 4750, price: 475 },
  { id: "elite-multishot-1", categoryId: "elite-multishot", name: "12 Shots (Raider)", content: "1 PC · 1 Box", mrp: 1800, price: 180 },
  { id: "elite-multishot-2", categoryId: "elite-multishot", name: "12 Shots (Multi Crackling)", content: "1 PC · 1 Box", mrp: 2200, price: 220 },
  { id: "elite-multishot-3", categoryId: "elite-multishot", name: "30 Shots (Multi Crackling)", content: "1 PC · 1 Box", mrp: 5000, price: 500 },
  { id: "elite-multishot-4", categoryId: "elite-multishot", name: "60 Shots(Multi Crackling)", content: "1 PC · 1 Box", mrp: 10000, price: 1000 },
  { id: "elite-multishot-5", categoryId: "elite-multishot", name: "120 Shots (Multi Crackling)", content: "1 PC · 1 Box", mrp: 20000, price: 2000 },
  { id: "elite-multishot-6", categoryId: "elite-multishot", name: "240 Shots (Multi Crackling)", content: "1 PC · 1 Box", mrp: 40000, price: 4000 },
  { id: "elite-giftbox-1", categoryId: "elite-giftbox", name: "Gift Box- 25 Items", content: "1 Box", mrp: 4500, price: 450 },
  { id: "elite-giftbox-2", categoryId: "elite-giftbox", name: "Gift Box -30 Items", content: "1 Box", mrp: 5500, price: 550 },
  { id: "elite-giftbox-3", categoryId: "elite-giftbox", name: "Gift Box -35 Items", content: "1 Box", mrp: 8000, price: 800 },
  { id: "elite-giftbox-4", categoryId: "elite-giftbox", name: "Gift Box- 40 Items", content: "1 Box", mrp: 9000, price: 900 },
  { id: "elite-giftbox-5", categoryId: "elite-giftbox", name: "Gift Box- 50 Items", content: "1 Box", mrp: 12000, price: 1200 },
];
